version: "3.8"

services:
  proxy:
    image: adalia.info/proxy:latest
    container_name: adalia.info_proxy
    build: ./proxy
    depends_on:
      - server
      - client
    ports:
      - "80:80"

  mongodb:
    # port 27017
    image: mongo:5.0.2
    container_name: adalia.info_mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb_data:/data/db

  server:
    # port 5000
    image: adalia.info/server:latest
    container_name: adalia.info_server
    build: ./server
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb:27017
      - ASTEROID_DATA_DUMP_URL=${ASTEROID_DATA_DUMP_URL}

  client:
    # port 80
    image: adalia.info/client:latest
    container_name: adalia.info_client
    build: ./client

volumes:
  mongodb_data:
